// Central mapping from the app's semantic icon names to lucide-react glyphs,
// chosen to match the Material icons used in the original Compose UI.
export {
  Globe as IcMap,
  Clock as IcSchedule,
  Box as IcAr,
  User as IcProfile,
  Search as IcSearch,
  SlidersHorizontal as IcTune,
  Layers as IcLayers,
  Map as IcMapStyle,
  LocateFixed as IcMyLocation,
  ArrowRight as IcArrowForward,
  ArrowLeft as IcArrowBack,
  PlaneTakeoff as IcFlightTakeoff,
  PlaneLanding as IcFlightLand,
  Plane as IcFlight,
  Share2 as IcShare,
  Bookmark as IcBookmark,
  ArrowUpRight as IcArrowOutward,
  Gauge as IcSpeed,
  Ruler as IcStraighten,
  ArrowUpDown as IcSwapVert,
  Navigation as IcNavigation,
  ChevronDown as IcExpandMore,
  ChevronRight as IcChevronRight,
  Check as IcCheck,
  X as IcClose,
  Zap as IcBolt,
  Filter as IcFilter,
  Bell as IcNotifications,
  Moon as IcDarkMode,
  Info as IcInfo,
  Star as IcStar,
} from 'lucide-react'
